### ✅ADS1115 (ANALOG TO DIGITAL CONVERTER FOR BATTERY LEVEL)--------------
GET http://10.0.0.188:5500/api/ads1115/level/

### 
GET http://10.0.0.188:5500/api/ads1115/start/

###
GET http://10.0.0.188:5500/api/ads1115/pause/




### ✅MCP3008 (ANALOG TO DIGITAL CONVERTER FOR BATTERY LEVEL)--------------
GET http://10.0.0.188:5500/api/mcp3008/level/

### 
GET http://10.0.0.188:5500/api/mcp3008/start/

###
GET http://10.0.0.188:5500/api/mcp3008/pause/



### ✅GPS------------------------------------------------------------------
GET http://10.0.0.188:5500/api/gps/location/ 

###
GET http://10.0.0.188:5500/api/gps/last_saved/

###
GET http://10.0.0.188:5500/api/gps/cancel_stream/

###
GET http://10.0.0.188:5500/api/gps/stream/ 

###
GET http://10.0.0.188:5500/api/gps/status/ 




### GSM--------------------------------------------------------------------
PATCH http://10.0.0.188:5500/api/gsm/config/

###
GET http://10.0.0.188:5500/api/gsm/connect/

###
GET http://10.0.0.188:5500/api/gsm/disconnect/




### ✅LED------------------------------------------------------------------
GET http://10.0.0.188:5500/api/led/on/  

###
GET http://10.0.0.188:5500/api/led/off/ 

###
GET http://10.0.0.188:5500/api/led/blink/

###
GET http://10.0.0.188:5500/api/led/status/ 




### ✅LOGS-----------------------------------------------------------------
GET http://10.0.0.188:5500/api/logs?page=2&limit=11




### NFC PN532--------------------------------------------------------------
GET http://10.0.0.188:5500/api/pn532/reads/

###
POST http://10.0.0.188:5500/api/pn532/write/
Content-Type: application/json
Accept: application/json

{
    "text": "hey there user",
}

###
GET http://10.0.0.188:5500/api/pn532/pause/

###
GET http://10.0.0.188:5500/api/pn532/stats/




###  RFID RFC522-----------------------------------------------------------
GET http://10.0.0.188:5500/api/mfrc522/reads/

###
POST http://10.0.0.188:5500/api/mfrc522/write/
Content-Type: application/json
Accept: application/json

{
    "data": "hello world user 2"
}

###
GET http://10.0.0.188:5500/api/mfrc522/pause/

###
GET http://10.0.0.188:5500/api/mfrc522/stats/




### ✅APP--------------------------------------------------------------------
GET http://10.0.0.188:5500/ping/
